import "server-only";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import type { InvoiceLine } from "@/db/schema";
import { formatCents, formatInvoiceNumber, formatMinutes, type InvoiceRow } from "./timebilling";

/**
 * Invoice PDF (M7, ADR-0030) — pdf-lib, same posture as the e-sign stamper
 * (ADR-0024): pure JS, standard fonts, generated on demand from the invoice
 * row. Never stored — the row is the source of truth and the PDF is
 * deterministic, so regenerating beats retaining another S3 object.
 */

export type InvoicePdfInput = {
  invoice: Pick<
    InvoiceRow,
    | "number"
    | "status"
    | "issueDate"
    | "dueDate"
    | "lines"
    | "subtotalCents"
    | "taxLabel"
    | "taxCents"
    | "totalCents"
    | "notes"
  >;
  firmName: string;
  clientName: string;
  clientAddress: string | null;
};

const INK = rgb(0.1, 0.12, 0.18);
const MUTED = rgb(0.45, 0.48, 0.55);
const RULE = rgb(0.8, 0.82, 0.86);
const LEFT = 56;
const RIGHT = 556;
const PAGE: [number, number] = [612, 792]; // US Letter
const BOTTOM_MARGIN = 90;

export async function generateInvoicePdf(input: InvoicePdfInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const inv = input.invoice;

  let page = pdf.addPage(PAGE);
  let y = 720;
  const newPage = () => {
    page = pdf.addPage(PAGE);
    y = 740;
  };

  // Header
  page.drawText(input.firmName, { x: LEFT, y, size: 18, font: bold, color: INK });
  page.drawText("INVOICE", { x: RIGHT - bold.widthOfTextAtSize("INVOICE", 16), y, size: 16, font: bold, color: MUTED });
  y -= 18;
  page.drawLine({ start: { x: LEFT, y }, end: { x: RIGHT, y }, thickness: 1, color: RULE });
  y -= 26;

  const meta: [string, string][] = [
    ["Invoice number", formatInvoiceNumber(inv.number)],
    ["Issue date", inv.issueDate],
    ["Due date", inv.dueDate ?? "On receipt"],
    ["Billed to", input.clientName],
  ];
  if (input.clientAddress) meta.push(["Address", input.clientAddress]);
  if (inv.status === "void") meta.push(["Status", "VOID"]);
  for (const [label, value] of meta) {
    page.drawText(label.toUpperCase(), { x: LEFT, y, size: 8, font: bold, color: MUTED });
    page.drawText(value, { x: LEFT + 110, y, size: 11, font, color: INK });
    y -= 18;
  }
  y -= 14;

  // Line-item table
  const cols = { desc: LEFT, time: 380, rate: 440, amount: RIGHT };
  const header = () => {
    page.drawText("DESCRIPTION", { x: cols.desc, y, size: 8, font: bold, color: MUTED });
    page.drawText("TIME", { x: cols.time, y, size: 8, font: bold, color: MUTED });
    page.drawText("RATE/H", { x: cols.rate, y, size: 8, font: bold, color: MUTED });
    drawRight(page, "AMOUNT", bold, 8, cols.amount, y, MUTED);
    y -= 6;
    page.drawLine({ start: { x: LEFT, y }, end: { x: RIGHT, y }, thickness: 0.5, color: RULE });
    y -= 14;
  };
  header();

  for (const line of inv.lines as InvoiceLine[]) {
    const descLines = wrapText(line.description, font, 10, cols.time - cols.desc - 12);
    const rowHeight = descLines.length * 13 + 6;
    if (y - rowHeight < BOTTOM_MARGIN) {
      newPage();
      header();
    }
    for (let i = 0; i < descLines.length; i++) {
      page.drawText(descLines[i], { x: cols.desc, y: y - i * 13, size: 10, font, color: INK });
    }
    page.drawText(formatMinutes(line.minutes), { x: cols.time, y, size: 10, font, color: INK });
    page.drawText(formatCents(line.rateCents), { x: cols.rate, y, size: 10, font, color: INK });
    drawRight(page, formatCents(line.amountCents), font, 10, cols.amount, y, INK);
    y -= rowHeight;
  }

  // Totals
  y -= 4;
  if (y < BOTTOM_MARGIN + 70) newPage();
  page.drawLine({ start: { x: 380, y }, end: { x: RIGHT, y }, thickness: 0.5, color: RULE });
  y -= 16;
  const totals: [string, string, PDFFont][] = [
    ["Subtotal", formatCents(inv.subtotalCents), font],
    [inv.taxLabel, formatCents(inv.taxCents), font],
    ["Total (CAD)", formatCents(inv.totalCents), bold],
  ];
  for (const [label, value, f] of totals) {
    page.drawText(label, { x: 380, y, size: 11, font: f, color: INK });
    drawRight(page, value, f, 11, cols.amount, y, INK);
    y -= 18;
  }

  if (inv.notes) {
    y -= 10;
    if (y < BOTTOM_MARGIN + 30) newPage();
    page.drawText("NOTES", { x: LEFT, y, size: 8, font: bold, color: MUTED });
    y -= 14;
    for (const line of wrapText(inv.notes, font, 10, RIGHT - LEFT)) {
      if (y < BOTTOM_MARGIN) newPage();
      page.drawText(line, { x: LEFT, y, size: 10, font, color: INK });
      y -= 13;
    }
  }

  page.drawText(`Generated by ${input.firmName} via Accountant CRM.`, {
    x: LEFT,
    y: 56,
    size: 8,
    font,
    color: MUTED,
  });

  return pdf.save();
}

function drawRight(
  page: PDFPage,
  text: string,
  font: PDFFont,
  size: number,
  rightX: number,
  y: number,
  color: ReturnType<typeof rgb>
) {
  page.drawText(text, { x: rightX - font.widthOfTextAtSize(text, size), y, size, font, color });
}

/** Greedy word-wrap (long tokens hard-break). */
function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = [];
  let cur = "";
  for (const word of text.split(/\s+/)) {
    const test = cur ? `${cur} ${word}` : word;
    if (font.widthOfTextAtSize(test, size) <= maxWidth) {
      cur = test;
      continue;
    }
    if (cur) lines.push(cur);
    if (font.widthOfTextAtSize(word, size) <= maxWidth) {
      cur = word;
    } else {
      let chunk = "";
      for (const ch of word) {
        if (font.widthOfTextAtSize(chunk + ch, size) > maxWidth) {
          lines.push(chunk);
          chunk = ch;
        } else {
          chunk += ch;
        }
      }
      cur = chunk;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [""];
}
